baseURL = 'https://paractmol.cc/'
languageCode = 'en-us'
title = 'Paractmol: The ████ blog'
[taxonomies]
  series = 'series'
  tag = 'tags'

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"
